#  Created Base Image for all stages
FROM node:20-alpine As base
RUN apk add --no-cache libc6-compat
WORKDIR /usr/src/app
COPY . .
RUN npm install && \
    npm run build
CMD ["node_modules/.bin/next", "start"]